//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int id { get; set; }
        public string filename { get; set; }
        public Nullable<int> filesize { get; set; }
        public string web_path { get; set; }
        public string system_path { get; set; }
    }
}
