//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOrder
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> InventoryId { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Order Order { get; set; }
    }
}
