//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLInventoryView
    {
        public int InventoryId { get; set; }
        public string Product_name { get; set; }
        public string Product_sku { get; set; }
        public string Type { get; set; }
        public Nullable<int> Size { get; set; }
        public string Color { get; set; }
        public string Extras { get; set; }
    }
}
