//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLInventoryView3
    {
        public int OrderId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string RequestDate { get; set; }
        public string Email { get; set; }
        public string RequestedItems { get; set; }
        public Nullable<int> StreetSize { get; set; }
        public Nullable<int> Inventory1 { get; set; }
        public Nullable<int> Inventory2 { get; set; }
        public Nullable<int> Inventory3 { get; set; }
        public Nullable<int> Inventory4 { get; set; }
        public Nullable<int> Size1 { get; set; }
        public Nullable<int> Size2 { get; set; }
        public Nullable<int> Size3 { get; set; }
        public Nullable<int> Size4 { get; set; }
    }
}
